import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AppShell } from '@/components/layout/AppShell';
import PageFrame from '@/components/Pages/PageFrame';
import { HousekeepingSkeleton } from '@/components/ui/Skeleton';
import { formatTime12h } from '@/utils/time';
import {
  bulkUploadHousekeepingWorkbook,
  completeHousekeepingTask,
  createHousekeepingStaff,
  createHousekeepingTask,
  getHousekeepingOverview,
  updateHousekeepingStaffAttendance,
  updateHousekeepingTask,
} from '@/services/housekeeping';
import {
  CalendarDays,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock,
  Download,
  Edit,
  Eye,
  Plus,
  Search,
  ShieldAlert,
  Sparkles,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react';

// -- Types ------------------------------------------------------------------

interface Task {
  id?: string;
  taskCode?: string;
  taskName?: string;
  taskType?: string;
  sourceType?: string;
  area?: string;
  floor?: string;
  wing?: string;
  assignedTo?: string;
  assigneeEmployeeProfileId?: string;
  startTaskTime?: string;
  timeSlotLabel?: string;
  status?: string;
  roomName?: string;
  sourceBookingCode?: string;
  completedBy?: string;
  completedAt?: string;
  completedAtLabel?: string;
  dueAt?: string;
  dueAtLabel?: string;
  bookingDate?: string;
  bookingDateLabel?: string;
  bookingEndTimeLabel?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
}

interface Staff {
  id?: string;
  label?: string;
  fullName?: string;
  address?: string;
  phone?: string;
  email?: string;
  isActive?: boolean;
  attendanceStatus?: string;
  sourceType?: string;
}

interface Summary {
  pendingTasks: number;
  activeTasks: number;
  completedToday: number;
  bookingTriggers: number;
}

interface TaskFormState {
  taskName: string;
  taskType: string;
  area: string;
  floor: string;
  wing: string;
  assignedTo: string;
  assigneeEmployeeProfileId: string;
  startTaskTime: string;
  status: string;
}

interface StaffFormState {
  fullName: string;
  address: string;
  phone: string;
  email: string;
}

interface TabButtonProps {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}

interface ModalProps {
  title: string;
  subtitle: string;
  onClose: () => void;
  children: React.ReactNode;
  variant?: 'default' | 'alert';
}

interface TasksTableProps {
  tasks: Task[];
  onEdit: (task: Task) => void;
  onCancel: (task: Task) => Promise<void>;
  emptyText: string;
}

interface AutoTasksProps {
  tasks: Task[];
  onAssign: (task: Task) => void;
  onDone: (task: Task) => Promise<void>;
}

interface HistoryTableProps {
  tasks: Task[];
  month: string;
  year: string;
}

// -- Constants --------------------------------------------------------------

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const YEARS = ['2025', '2026', '2027'];
const TASK_TYPES = ['Meeting Room Cleaning', 'Desk Cleaning', 'Floor Cleaning', 'Washroom Cleaning', 'Custom'];
const FLOOR_OPTIONS = ['501', '601', '701'];
const WING_OPTIONS = ['A', 'B'];
const BULK_UPLOAD_INSTRUCTIONS_SHEET = 'Instructions';
const BULK_UPLOAD_STAFF_SHEET = 'Housekeeping Staff';
const BULK_UPLOAD_TASK_SHEET = 'Scheduled Tasks';
const BULK_UPLOAD_REFERENCE_SHEET = 'Dropdown Data';
const BULK_UPLOAD_STAFF_HEADERS = ['Full Name', 'Address', 'Phone', 'Email'];
const BULK_UPLOAD_TASK_HEADERS = ['Task Name', 'Start Task Time', 'Task Type', 'Area', 'Floor', 'Wing'];
const BULK_UPLOAD_INSTRUCTIONS: string[][] = [
  ['Sheet', 'Required fields', 'Optional fields', 'Format / notes'],
  ['Housekeeping Staff', 'Full Name, Address, Phone, Email', 'None', 'Keep the staff sheet to these 4 fields only.'],
  ['Scheduled Tasks', 'Task Name, Start Task Time', 'Task Type, Area, Floor, Wing', 'Start Task Time is the daily recurring time for the task. Leave it blank or enter a time like 08:30 AM.'],
  ['Fill format', 'One record per row', 'Blank rows are ignored', 'Do not rename the sheet names or header labels.'],
  ['Template scope', 'Required columns only', 'Do not add Due At, Status, Notes, Assigned To, or Assigned Staff Email unless you later need them manually', 'The importer still accepts extra columns, but the template does not include them.'],
  ['Dropdown data', 'Task Type, Floor, Wing', 'Use the values listed in the Dropdown Data sheet', 'The workbook includes the allowed choices for the task sheet.'],
];

const NOW = new Date();
const DEFAULT_HISTORY_MONTH = MONTHS[NOW.getMonth()];
const DEFAULT_HISTORY_YEAR = String(NOW.getFullYear());

// -- Helpers ----------------------------------------------------------------

function taskFormState(): TaskFormState {
  return {
    taskName: '',
    taskType: 'Meeting Room Cleaning',
    area: '',
    floor: '',
    wing: '',
    assignedTo: '',
    assigneeEmployeeProfileId: '',
    startTaskTime: '',
    status: 'Pending',
  };
}

function staffFormState(): StaffFormState {
  return { fullName: '', address: '', phone: '', email: '' };
}

function getDateValue(task: Task): string | null {
  return task.completedAt || task.dueAt || task.bookingDate || task.createdAt || null;
}

function monthOf(value: string | null | undefined): string {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? MONTHS[date.getMonth()] : '';
}

function yearOf(value: string | null | undefined): string {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? String(date.getFullYear()) : '';
}

function statusBadge(status?: string): string {
  if (status === 'Completed') return 'bg-green-50 text-green-600 border-green-200';
  if (status === 'In Progress') return 'bg-blue-50 text-blue-600 border-blue-200';
  if (status === 'Assigned') return 'bg-sky-50 text-sky-600 border-sky-200';
  if (status === 'Cancelled') return 'bg-slate-100 text-slate-500 border-slate-200';
  return 'bg-amber-50 text-amber-600 border-amber-200';
}

// -- Error Boundary ---------------------------------------------------------

interface ErrorBoundaryProps {
  children: React.ReactNode;
}

interface ErrorBoundaryState {
  error: Error | null;
  errorInfo: React.ErrorInfo | null;
}

class HousekeepingErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { error: null, errorInfo: null };
  }

  static getDerivedStateFromError(error: Error): Partial<ErrorBoundaryState> {
    return { error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo): void {
    this.setState({ errorInfo });
    console.error('[HousekeepingPage] render error:', error, errorInfo);
  }

  render(): React.ReactNode {
    if (this.state.error) {
      return (
        <AppShell>
          <div className="p-2 lg:p-2.5">
            <PageFrame>
              <div className="mx-auto max-w-4xl rounded-3xl border border-red-200 bg-white p-6 shadow-sm">
                <div className="flex items-start gap-4">
                  <div className="rounded-2xl bg-red-50 p-3 text-red-600">
                    <ShieldAlert size={28} />
                  </div>
                  <div className="flex-1">
                    <h1 className="text-2xl font-black tracking-tight text-red-900">
                      Housekeeping crashed while rendering
                    </h1>
                    <p className="mt-2 text-sm font-medium text-slate-600">
                      The page hit a render-time error. The details below should help us identify the
                      cause immediately.
                    </p>
                  </div>
                </div>

                <div className="mt-6 rounded-2xl border border-red-100 bg-red-50 p-4">
                  <p className="text-[10px] font-black uppercase tracking-widest text-red-600">
                    Error message
                  </p>
                  <p className="mt-2 text-sm font-semibold text-red-900">
                    {this.state.error?.message || 'Unknown error'}
                  </p>
                </div>

                {this.state.error?.stack ? (
                  <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-500">
                      Stack trace
                    </p>
                    <pre className="mt-2 overflow-auto whitespace-pre-wrap break-words text-[11px] leading-relaxed text-slate-700">
                      {this.state.error.stack}
                    </pre>
                  </div>
                ) : null}

                {this.state.errorInfo?.componentStack ? (
                  <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-500">
                      Component stack
                    </p>
                    <pre className="mt-2 overflow-auto whitespace-pre-wrap break-words text-[11px] leading-relaxed text-slate-700">
                      {this.state.errorInfo.componentStack}
                    </pre>
                  </div>
                ) : null}
              </div>
            </PageFrame>
          </div>
        </AppShell>
      );
    }

    return this.props.children;
  }
}

// -- Inner Page Component ---------------------------------------------------

function HousekeepingPageInner() {
  const [activeTab, setActiveTab] = useState('scheduled');
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('All Status');
  const [historyMonth, setHistoryMonth] = useState(DEFAULT_HISTORY_MONTH);
  const [historyYear, setHistoryYear] = useState(DEFAULT_HISTORY_YEAR);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');
  const [tasks, setTasks] = useState<Task[]>([]);
  const [staff, setStaff] = useState<Staff[]>([]);
  const [summary, setSummary] = useState<Summary>({
    pendingTasks: 0,
    activeTasks: 0,
    completedToday: 0,
    bookingTriggers: 0,
  });
  const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);
  const [isStaffModalOpen, setIsStaffModalOpen] = useState(false);
  const [isBulkUploadModalOpen, setIsBulkUploadModalOpen] = useState(false);
  const [isStaffListOpen, setIsStaffListOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [assigningTask, setAssigningTask] = useState<Task | null>(null);
  const [taskForm, setTaskForm] = useState<TaskFormState>(taskFormState());
  const [staffForm, setStaffForm] = useState<StaffFormState>(staffFormState());
  const [bulkUploadFile, setBulkUploadFile] = useState<File | null>(null);
  const [bulkUploadMessage, setBulkUploadMessage] = useState('');
  const [isBulkUploading, setIsBulkUploading] = useState(false);

  useEffect(() => {
    let isMounted = true;
    (async () => {
      setIsLoading(true);
      try {
        const response = await getHousekeepingOverview();
        const data = response?.data || {};
        if (!isMounted) return;
        setTasks(Array.isArray(data.tasks) ? data.tasks : []);
        setStaff(Array.isArray(data.staff) ? data.staff : []);
        setSummary({
          pendingTasks: Number(data.summary?.pendingTasks || 0),
          activeTasks: Number(data.summary?.activeTasks || 0),
          completedToday: Number(data.summary?.completedToday || 0),
          bookingTriggers: Number(data.summary?.bookingTriggers || 0),
        });
      } catch (error: any) {
        if (!isMounted) return;
        setErrorMessage(error?.message || 'Failed to load housekeeping data.');
      } finally {
        if (isMounted) setIsLoading(false);
      }
    })();
    return () => { isMounted = false; };
  }, []);

  const manualTasks = useMemo(
    () =>
      tasks.filter(
        (task) =>
          task.sourceType !== 'booking' &&
          task.status !== 'Completed' &&
          task.status !== 'Cancelled' &&
          (statusFilter === 'All Status' || task.status === statusFilter) &&
          [task.taskName, task.area, task.floor, task.wing, task.assignedTo].some((v) =>
            String(v || '').toLowerCase().includes(searchQuery.toLowerCase()),
          ),
      ),
    [tasks, statusFilter, searchQuery],
  );

  const bookingTasks = useMemo(
    () =>
      tasks.filter(
        (task) =>
          task.sourceType === 'booking' &&
          task.status !== 'Completed' &&
          task.status !== 'Cancelled' &&
          [task.roomName, task.taskName, task.sourceBookingCode, task.floor, task.wing, task.assignedTo].some((v) =>
            String(v || '').toLowerCase().includes(searchQuery.toLowerCase()),
          ),
      ),
    [tasks, searchQuery],
  );

  const historyTasks = useMemo(
    () =>
      tasks.filter(
        (task) =>
          task.status === 'Completed' &&
          monthOf(getDateValue(task)) === historyMonth &&
          yearOf(getDateValue(task)) === historyYear &&
          [task.taskName, task.area, task.floor, task.wing, task.completedBy].some((v) =>
            String(v || '').toLowerCase().includes(searchQuery.toLowerCase()),
          ),
      ),
    [tasks, historyMonth, historyYear, searchQuery],
  );

  const activeStaff = useMemo(() => staff.filter((item) => item.isActive !== false), [staff]);
  const presentStaff = useMemo(
    () => activeStaff.filter((item) => String(item.attendanceStatus || 'Present') === 'Present'),
    [activeStaff],
  );
  const selectedStaff = presentStaff.find((item) => item.id === taskForm.assigneeEmployeeProfileId);
  async function saveTask(event: React.FormEvent): Promise<void> {
    event.preventDefault();
    try {
      const assigneeEmployeeProfileId = selectedStaff ? taskForm.assigneeEmployeeProfileId : null;
      const payload = {
        taskName: taskForm.taskName,
        taskType: taskForm.taskType,
        area: taskForm.area,
        floor: taskForm.floor,
        wing: taskForm.wing,
        assignedTo: selectedStaff?.label || (editingTask ? 'Unassigned' : taskForm.assignedTo || 'Unassigned'),
        assigneeEmployeeProfileId,
        startTaskTime: taskForm.startTaskTime,
        timeSlotLabel: taskForm.startTaskTime,
        status: editingTask ? taskForm.status : 'Pending',
        sourceType: 'manual',
        isAutoGenerated: false,
      };
      if (editingTask?.id) { await updateHousekeepingTask(editingTask.id, payload); }
      else { await createHousekeepingTask(payload); }
      setIsTaskModalOpen(false);
      setEditingTask(null);
      setTaskForm(taskFormState());
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to save task.');
    }
  }

  async function saveStaff(event: React.FormEvent): Promise<void> {
    event.preventDefault();
    try {
      await createHousekeepingStaff(staffForm);
      setIsStaffModalOpen(false);
      setStaffForm(staffFormState());
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to add housekeeping staff.');
    }
  }

  function editTask(task: Task): void {
    setEditingTask(task);
    setTaskForm({
      taskName: task.taskName || '',
      taskType: task.taskType || 'Meeting Room Cleaning',
      area: task.area || '',
      floor: task.floor || '',
      wing: task.wing || '',
      assignedTo: task.assignedTo || '',
      assigneeEmployeeProfileId: presentStaff.some((item) => item.id === task.assigneeEmployeeProfileId)
        ? task.assigneeEmployeeProfileId || ''
        : '',
      startTaskTime: task.startTaskTime || task.timeSlotLabel || '',
      status: task.status || 'Pending',
    });
    setIsTaskModalOpen(true);
  }

  async function cancelTask(task: Task): Promise<void> {
    const confirmed = window.confirm('Cancel this housekeeping task?');
    if (!confirmed) return;
    try {
      await updateHousekeepingTask(task.id!, { status: 'Cancelled' });
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to cancel task.');
    }
  }

  async function assignTask(): Promise<void> {
    if (!assigningTask || !taskForm.assigneeEmployeeProfileId) return;
    try {
      const nextStaff = presentStaff.find((item) => item.id === taskForm.assigneeEmployeeProfileId);
      await updateHousekeepingTask(assigningTask.id!, {
        assignedTo: nextStaff?.label || 'Unassigned',
        assigneeEmployeeProfileId: taskForm.assigneeEmployeeProfileId,
        status: assigningTask.status === 'Pending' ? 'Assigned' : assigningTask.status,
      });
      setAssigningTask(null);
      setTaskForm(taskFormState());
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to assign task.');
    }
  }

  async function markDone(task: Task): Promise<void> {
    try {
      await completeHousekeepingTask(task.id!, {
        completionNote: 'Marked complete after verbal confirmation.',
      });
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to complete task.');
    }
  }

  async function saveStaffAttendance(staffMember: Staff, attendanceStatus: string): Promise<void> {
    try {
      await updateHousekeepingStaffAttendance(staffMember.id!, { attendanceStatus });
      setErrorMessage('');
    } catch (error: any) {
      setErrorMessage(error?.message || 'Failed to update staff attendance.');
    }
  }

  async function downloadBulkTemplate(): Promise<void> {
    const XLSX = await import('xlsx');
    const wb = XLSX.utils.book_new();

    const instructionsSheet = XLSX.utils.aoa_to_sheet([
      ['Housekeeping bulk upload'],
      ...BULK_UPLOAD_INSTRUCTIONS,
    ]);

    const staffSheet = XLSX.utils.aoa_to_sheet([BULK_UPLOAD_STAFF_HEADERS]);
    const taskSheet = XLSX.utils.aoa_to_sheet([BULK_UPLOAD_TASK_HEADERS]);

    const referenceSheet = XLSX.utils.aoa_to_sheet([
      ['Task Type', 'Floor', 'Wing'],
      [TASK_TYPES[0], FLOOR_OPTIONS[0], WING_OPTIONS[0]],
      [TASK_TYPES[1], FLOOR_OPTIONS[1], WING_OPTIONS[1]],
      [TASK_TYPES[2], FLOOR_OPTIONS[2], ''],
      [TASK_TYPES[3], '', ''],
      [TASK_TYPES[4], '', ''],
    ]);

    XLSX.utils.book_append_sheet(wb, instructionsSheet, BULK_UPLOAD_INSTRUCTIONS_SHEET);
    XLSX.utils.book_append_sheet(wb, staffSheet, BULK_UPLOAD_STAFF_SHEET);
    XLSX.utils.book_append_sheet(wb, taskSheet, BULK_UPLOAD_TASK_SHEET);
    XLSX.utils.book_append_sheet(wb, referenceSheet, BULK_UPLOAD_REFERENCE_SHEET);

    const workbookBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([workbookBuffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    const objectUrl = window.URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = objectUrl;
    anchor.download = 'housekeeping-bulk-upload-template.xlsx';
    anchor.click();
    window.URL.revokeObjectURL(objectUrl);
  }

  async function handleBulkUpload(event: React.FormEvent): Promise<void> {
    event.preventDefault();

    if (!bulkUploadFile) {
      setErrorMessage('Select a housekeeping workbook to upload.');
      return;
    }

    alert('Bulk upload is not available in demo mode. Workbook would be processed by the backend.');
    // Backend implementation:
    // try {
    //   setIsBulkUploading(true);
    //   const response = await bulkUploadHousekeepingWorkbook(bulkUploadFile);
    //   const data = response?.data || {};
    //   const staffSummary = data.staff || {};
    //   const taskSummary = data.tasks || {};
    //   const importedStaff = Number(staffSummary.created || 0) + Number(staffSummary.updated || 0);
    //   const importedTasks = Number(taskSummary.created || 0);
    //   const warnings = [...(staffSummary.warnings || []), ...(taskSummary.warnings || [])];
    //   const warningPreview = warnings.slice(0, 3).join(' | ');
    //   setBulkUploadMessage(
    //     importedStaff + ' staff record(s) and ' + importedTasks + ' task(s) imported successfully.' +
    //     (warnings.length > 0 ? ' ' + warnings.length + ' row(s) skipped. ' + warningPreview : ''),
    //   );
    // } catch (error) {
    //   setErrorMessage(error?.message || 'Failed to import the housekeeping workbook.');
    // } finally {
    //   setIsBulkUploading(false);
    // }

    setBulkUploadFile(null);
    setIsBulkUploadModalOpen(false);
    setIsBulkUploading(false);
  }

  return (
    <AppShell>
      <div className="p-2 lg:p-2.5">
        <PageFrame>
          <div className="flex flex-col gap-4">

          {/* Header */}
          <div className="mb-3 flex items-center justify-between">
            <div>
              <h1 className="text-title font-pmedium text-primary uppercase">Housekeeping</h1>
              <p className="text-xs font-pmedium text-slate-500 mt-1">
                Core Module - Administration Manager
              </p>
            </div>
          </div>

          {/* Staff Registry Summary */}
          {/* <div className="mb-6 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
              <div>
                <p className="text-[10px] font-black uppercase tracking-widest text-blue-500">Housekeeping Staff Registry</p>
                
                <p className="mt-1 text-xs font-medium text-slate-500">Add staff here. Managers can mark them present or absent before assigning daily tasks.</p>
              </div>
              <div className="text-right">
                <p className="text-3xl font-black text-slate-900">{activeStaff.length}</p>
                <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Registered staff</p>
              </div>
            </div>
            <div className="mt-4 flex flex-wrap gap-2">
              {activeStaff.length > 0
                ? activeStaff.map((item) => (
                    <span key={item.id} className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 text-xs font-bold text-slate-700">
                      {item.label}
                      <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-black uppercase tracking-widest">
                        {item.attendanceStatus || 'Present'}
                      </span>
                    </span>
                  ))
                : <div className="text-sm font-medium text-slate-400">No housekeeping staff added yet.</div>}
            </div>
          </div> */}

          {errorMessage ? <div className="mb-6 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{errorMessage}</div> : null}
          {bulkUploadMessage ? <div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{bulkUploadMessage}</div> : null}

          {/* ── Pill Tabs (DESIGN.md: pill-style with blue active bg) ── */}
          <div className="mb-3 flex flex-wrap gap-1.5 rounded-2xl border border-slate-100 bg-white p-1 shadow-sm">
            {[
              { key: 'scheduled', label: 'Daily Scheduled Tasks' },
              { key: 'auto', label: 'Booking-Based Tasks', badge: 'AUTO' },
              { key: 'history', label: 'Task History' },
            ].map((tab) => (
              <button
                key={tab.key}
                type="button"
                onClick={() => setActiveTab(tab.key)}
                className={`flex-1 rounded-xl px-4 py-2 text-[10px] font-pbold font-bold uppercase tracking-widest transition-all flex items-center justify-center gap-1.5 whitespace-nowrap ${
                   activeTab === tab.key
                     ? 'bg-[#2563EB] text-white shadow-sm'
                     : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900'
                 }`}
               >
                 {tab.label}
                 {tab.badge ? (
                   <span className="flex items-center gap-1 rounded-md bg-red-100 px-1.5 py-0.5 text-red-600 text-[9px] font-pbold font-bold uppercase tracking-widest">
                    <Zap size={9} />{tab.badge}
                  </span>
                ) : null}
              </button>
            ))}
          </div>

          {/* ── Stat Cards (DESIGN.md: border-l-4 accent per card) ── */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3 shrink-0">
            {[
              { key: 'pending', label: 'Scheduled (Pending)', value: String(summary.pendingTasks), icon: ClipboardList },
              { key: 'bookingTriggers', label: 'Booking Triggers', value: String(summary.bookingTriggers), icon: Zap },
              { key: 'active', label: 'In Progress', value: String(summary.activeTasks), icon: Clock },
              { key: 'completed', label: 'Completed Today', value: String(summary.completedToday), icon: Sparkles },
            ].map((card, idx) => {
              const Icon = card.icon;
              const borderColors = ['', 'border-l-4 border-l-amber-500', 'border-l-4 border-l-red-500', 'border-l-4 border-l-blue-500', 'border-l-4 border-l-emerald-500'];
              const iconClasses = ['bg-slate-50 text-slate-600', 'bg-amber-50 text-amber-600', 'bg-red-50 text-red-600', 'bg-blue-50 text-blue-600', 'bg-emerald-50 text-emerald-600'];
              return (
                <div key={card.key} className={`bg-white p-5 rounded-[2rem] border border-slate-100 shadow-sm flex justify-between items-center transition-all hover:shadow-md ${borderColors[idx] || ''}`}>
                  <div className="min-w-0">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{card.label}</p>
                    <p className="text-[15px] font-black text-slate-900">{card.value}</p>
                  </div>
                  <div className={`p-2 rounded-2xl ${iconClasses[idx] || 'bg-slate-50 text-slate-600'} shrink-0`}>
                    <Icon size={16} />
                  </div>
                </div>
              );
            })}
          </div>

          {/* ── Data Panel ── */}
          <div className="bg-white/80 backdrop-blur-md rounded-2xl border border-slate-100 shadow-sm overflow-hidden flex flex-col min-h-[500px]">
            {/* ── Panel Header ── */}
            <div className="p-3 sm:p-4 lg:p-5 border-b border-slate-100/60 flex flex-col xl:flex-row justify-between items-center gap-4 bg-slate-50/50">
              <div className="flex flex-wrap items-center gap-3 w-full xl:w-auto">
                {activeTab === 'scheduled' ? (
                  <select
                    className="w-full sm:w-44 px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-[11px] font-semibold text-slate-700 outline-none cursor-pointer"
                    value={statusFilter}
                    onChange={(event) => setStatusFilter(event.target.value)}
                  >
                    <option>All Status</option>
                    <option>Pending</option>
                    <option>Assigned</option>
                    <option>In Progress</option>
                    <option>Completed</option>
                  </select>
                ) : null}

                {activeTab === 'history' ? (
                  <>
                    <select className="px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-[11px] font-semibold text-slate-700 outline-none cursor-pointer" value={historyMonth} onChange={(event) => setHistoryMonth(event.target.value)}>
                      {MONTHS.map((m) => <option key={m}>{m}</option>)}
                    </select>
                    <select className="px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-[11px] font-semibold text-slate-700 outline-none cursor-pointer" value={historyYear} onChange={(event) => setHistoryYear(event.target.value)}>
                      {YEARS.map((y) => <option key={y}>{y}</option>)}
                    </select>
                  </>
                ) : null}
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <div className="relative min-w-[200px]">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                  <input
                    type="text"
                    placeholder="Search task or area..."
                    className="w-full pl-10 pr-4 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-medium outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-[#2563EB]/20"
                    value={searchQuery}
                    onChange={(event) => setSearchQuery(event.target.value)}
                  />
                </div>
                <button
                  onClick={() => setIsStaffListOpen(true)}
                  className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-[11px] font-semibold text-slate-700 shadow-sm transition hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700 whitespace-nowrap"
                >
                  <Eye size={16} />
                  Show Staff
                </button>
                <button
                  onClick={() => { setStaffForm(staffFormState()); setIsStaffModalOpen(true); }}
                  className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-[11px] font-semibold text-slate-700 shadow-sm transition hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700 whitespace-nowrap"
                >
                  <Users size={16} />
                  Add Staff
                </button>
                <button
                  onClick={() => { setBulkUploadMessage(''); setBulkUploadFile(null); setIsBulkUploadModalOpen(true); }}
                  className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-[11px] font-semibold text-slate-700 shadow-sm transition hover:border-emerald-300 hover:bg-emerald-50 hover:text-emerald-700 whitespace-nowrap"
                >
                  <Upload size={16} />
                  Bulk Upload
                </button>
                <button
                  onClick={() => { setEditingTask(null); setTaskForm(taskFormState()); setIsTaskModalOpen(true); }}
                  className="inline-flex items-center justify-center gap-1.5 rounded-2xl bg-[#2563EB] px-4 py-2.5 text-[10px] font-bold text-white shadow-sm transition-all hover:bg-blue-700 active:scale-95 whitespace-nowrap"
                >
                  <Plus size={13} strokeWidth={3} />
                  Add Scheduled Task
                </button>
              </div>
            </div>

            {isLoading ? <HousekeepingSkeleton /> : null}

            {!isLoading && activeTab === 'scheduled' ? (
              <TasksTable tasks={manualTasks} onEdit={editTask} onCancel={cancelTask} emptyText="No scheduled tasks found." />
            ) : null}

            {!isLoading && activeTab === 'auto' ? (
              <AutoTasks
                tasks={bookingTasks}
                onAssign={(task) => { setAssigningTask(task); setTaskForm((prev) => ({ ...prev, assigneeEmployeeProfileId: task.assigneeEmployeeProfileId || '' })); }}
                onDone={markDone}
              />
            ) : null}

            {!isLoading && activeTab === 'history' ? (
              <HistoryTable tasks={historyTasks} month={historyMonth} year={historyYear} />
            ) : null}
          </div>
          </div>
        </PageFrame>

        {/* -- Task Modal --------------------------------------------------- */}
        {isTaskModalOpen ? (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0F172A]/40 p-4 backdrop-blur-sm">
            <div className="flex h-full max-h-[88vh] w-full max-w-2xl flex-col overflow-hidden rounded-[2.5rem] bg-white shadow-2xl border border-white/70">
              <div className="flex items-start justify-between gap-4 border-b border-slate-100 bg-blue-50/70 px-6 py-5 lg:px-8 lg:py-6">
                <div>
                  <h2 className="flex items-center gap-2 text-xl font-pmedium text-primary">
                    {editingTask ? 'Edit Scheduled Task' : 'New Scheduled Task'}
                  </h2>
                  <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">Routine Housekeeping Assignment</p>
                </div>
                <button
                  onClick={() => { setIsTaskModalOpen(false); setEditingTask(null); setTaskForm(taskFormState()); }}
                  className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white p-2 text-slate-500 transition-all hover:bg-slate-100"
                >
                  <X size={18} />
                </button>
              </div>

              <form onSubmit={saveTask} className="flex min-h-0 flex-1 flex-col overflow-hidden">
                <div className="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-6 py-6 lg:px-8 lg:py-7">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Task Type *</label>
                    <select
                      required
                      className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none transition-all focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                      value={taskForm.taskType}
                      onChange={(event) => setTaskForm({ ...taskForm, taskType: event.target.value })}
                    >
                      {TASK_TYPES.map((type) => <option key={type}>{type}</option>)}
                    </select>
                  </div>

                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">
                      {taskForm.taskType === 'Custom' ? 'Custom Task Name *' : 'Task Name *'}
                    </label>
                    <input required type="text" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none transition-all focus:border-blue-500 focus:ring-1 focus:ring-blue-500" value={taskForm.taskName} onChange={(event) => setTaskForm({ ...taskForm, taskName: event.target.value })} />
                  </div>

                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Area / Zone *</label>
                    <input required type="text" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none transition-all focus:border-blue-500 focus:ring-1 focus:ring-blue-500" value={taskForm.area} onChange={(event) => setTaskForm({ ...taskForm, area: event.target.value })} />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Floor *</label>
                      <select required className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={taskForm.floor} onChange={(event) => setTaskForm({ ...taskForm, floor: event.target.value })}>
                        <option value="">Select Floor...</option>
                        {FLOOR_OPTIONS.map((floor) => <option key={floor} value={floor}>{floor}</option>)}
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Wing *</label>
                      <select required className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={taskForm.wing} onChange={(event) => setTaskForm({ ...taskForm, wing: event.target.value })}>
                        <option value="">Select Wing...</option>
                        {WING_OPTIONS.map((wing) => <option key={wing} value={wing}>{wing}</option>)}
                      </select>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Assign To (Staff)</label>
                      <select className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={taskForm.assigneeEmployeeProfileId} onChange={(event) => { const next = presentStaff.find((item) => item.id === event.target.value); setTaskForm({ ...taskForm, assigneeEmployeeProfileId: event.target.value, assignedTo: next?.label || '' }); }}>
                        <option value="">Select Staff...</option>
                        {presentStaff.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Start Task Time *</label>
                      <input required type="time" step="300" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={taskForm.startTaskTime} onChange={(event) => setTaskForm({ ...taskForm, startTaskTime: event.target.value })} />
                    </div>
                  </div>

                  {editingTask ? (
                    <div className="space-y-2 border-t border-slate-100 pt-6">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Update Status</label>
                      <select className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-900 shadow-sm outline-none" value={taskForm.status} onChange={(event) => setTaskForm({ ...taskForm, status: event.target.value })}>
                        <option>Pending</option><option>Assigned</option><option>In Progress</option><option>Completed</option><option>Cancelled</option>
                      </select>
                    </div>
                  ) : null}
                </div>

                <div className="flex gap-4 border-t border-slate-100 px-6 py-6 lg:px-8">
                  <button type="button" onClick={() => { setIsTaskModalOpen(false); setEditingTask(null); setTaskForm(taskFormState()); }} className="flex-1 rounded-2xl bg-slate-100 py-4 font-black text-slate-700 transition-all hover:bg-slate-200">Cancel</button>
                  <button type="submit" className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-blue-600 py-4 font-black text-white shadow-sm transition-all hover:bg-blue-700"><Plus size={18} />{editingTask ? 'Update Task' : 'Save Task'}</button>
                </div>
              </form>
            </div>
          </div>
        ) : null}

        {/* -- Staff Modal -------------------------------------------------- */}
        {isStaffModalOpen ? (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0F172A]/40 p-4 backdrop-blur-sm">
            <div className="flex w-full max-w-2xl flex-col overflow-hidden rounded-[2.5rem] bg-white shadow-2xl border border-white/70">
              <div className="flex items-start justify-between gap-4 border-b border-slate-100 bg-blue-50/70 px-6 py-5 lg:px-8 lg:py-6">
                <div>
                  <h2 className="flex items-center gap-2 text-xl font-pmedium text-primary"><Users size={20} /> Add Housekeeping Staff</h2>
                  <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">Basic details for task assignment</p>
                </div>
                <button onClick={() => { setIsStaffModalOpen(false); setStaffForm(staffFormState()); }} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white p-2 text-slate-500 transition-all hover:bg-slate-100"><X size={18} /></button>
              </div>
              <form onSubmit={saveStaff} className="flex min-h-0 flex-1 flex-col overflow-hidden">
                <div className="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-6 py-6 lg:px-8 lg:py-7">
                  <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Full Name *</label>
                      <input required type="text" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={staffForm.fullName} onChange={(event) => setStaffForm({ ...staffForm, fullName: event.target.value })} />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Address *</label>
                      <input required type="text" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={staffForm.address} onChange={(event) => setStaffForm({ ...staffForm, address: event.target.value })} />
                    </div>
                  </div>
                  <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Email</label>
                      <input type="email" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={staffForm.email} onChange={(event) => setStaffForm({ ...staffForm, email: event.target.value })} />
                    </div>
                    <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Phone *</label>
                      <input required type="tel" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={staffForm.phone} onChange={(event) => setStaffForm({ ...staffForm, phone: event.target.value })} />
                    </div>
                  </div>
                </div>
                <div className="flex gap-4 border-t border-slate-100 px-6 py-6 lg:px-8">
                  <button type="button" onClick={() => { setIsStaffModalOpen(false); setStaffForm(staffFormState()); }} className="flex-1 rounded-2xl bg-slate-100 py-4 font-black text-slate-700 transition-all hover:bg-slate-200">Cancel</button>
                  <button type="submit" className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-blue-600 py-4 font-black text-white shadow-sm transition-all hover:bg-blue-700"><Users size={18} /> Save Staff</button>
                </div>
              </form>
            </div>
          </div>
        ) : null}

        {/* -- Staff List Modal ---------------------------------------------- */}
        {isStaffListOpen ? (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0F172A]/40 p-4 backdrop-blur-sm">
            <div className="flex w-full max-w-2xl flex-col overflow-hidden rounded-[2.5rem] bg-white shadow-2xl border border-white/70">
              <div className="flex items-start justify-between gap-4 border-b border-slate-100 bg-blue-50/70 px-6 py-5 lg:px-8 lg:py-6">
                <div>
                  <h2 className="flex items-center gap-2 text-xl font-pmedium text-primary"><Users size={20} /> Housekeeping Staff</h2>
                  <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">Present or absent is managed here</p>
                </div>
                <button onClick={() => setIsStaffListOpen(false)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white p-2 text-slate-500 transition-all hover:bg-slate-100"><X size={18} /></button>
              </div>
              <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto px-6 py-6 lg:px-8 lg:py-7">
                {activeStaff.length > 0 ? activeStaff.map((member) => (
                  <div key={member.id} className="rounded-2xl border border-slate-200 p-5 shadow-sm">
                    <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                      <div>
                        <div className="flex flex-wrap items-center gap-2">
                          <h3 className="text-lg font-black text-slate-900">{member.fullName}</h3>
                          <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-widest`}>
                            {member.attendanceStatus || 'Present'}
                          </span>
                          {member.sourceType === 'legacy-employee-profile' ? <span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase tracking-widest text-slate-500">Legacy</span> : null}
                        </div>
                        <div className="mt-2 space-y-1 text-sm text-slate-600">
                          <p>{member.address || 'No address'}</p>
                          <p>{member.phone || 'No phone'}</p>
                          {member.email ? <p>{member.email}</p> : <p>No email</p>}
                        </div>
                      </div>
                      {member.sourceType === 'registry' ? (
                        <div className="flex gap-2">
                          <button type="button" onClick={() => saveStaffAttendance(member, 'Present')} className="rounded-xl border border-green-200 bg-green-50 px-4 py-2 text-xs font-black uppercase tracking-widest text-green-700">Present</button>
                          <button type="button" onClick={() => saveStaffAttendance(member, 'Absent')} className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-xs font-black uppercase tracking-widest text-red-700">Absent</button>
                        </div>
                      ) : null}
                    </div>
                  </div>
                )) : <div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm font-medium text-slate-400">No housekeeping staff added yet.</div>}
              </div>
            </div>
          </div>
        ) : null}

        {/* -- Bulk Upload Modal -------------------------------------------- */}
        {isBulkUploadModalOpen ? (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0F172A]/40 p-4 backdrop-blur-sm">
            <div className="flex w-full max-w-2xl flex-col overflow-hidden rounded-[2.5rem] bg-white shadow-2xl border border-white/70">
              <div className="flex items-start justify-between gap-4 border-b border-slate-100 bg-blue-50/70 px-6 py-5 lg:px-8 lg:py-6">
                <div>
                  <h2 className="flex items-center gap-2 text-xl font-pmedium text-primary"><Upload size={20} /> Bulk Upload</h2>
                  <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">One workbook with staff and scheduled tasks</p>
                </div>
                <button onClick={() => setIsBulkUploadModalOpen(false)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white p-2 text-slate-500 transition-all hover:bg-slate-100"><X size={18} /></button>
              </div>
              <form onSubmit={handleBulkUpload} className="flex min-h-0 flex-1 flex-col overflow-hidden">
                <div className="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-6 py-6 lg:px-8 lg:py-7">
                  {/* <div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800">
                    Download the workbook template, fill only the required fields shown in the <strong>Instructions</strong> sheet, then upload the completed file here.
                  </div> */}
                  <button type="button" onClick={downloadBulkTemplate} className="w-full rounded-2xl border bg-blue-600 bg-slate-100 px-5 py-4 text-sm font-black text-slate-700 transition-all hover:bg-slate-200 flex items-center justify-center gap-2">
                    <Download size={16} /> Download Template
                  </button>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Upload Workbook *</label>
                    <input
                      type="file"
                      accept=".xlsx,.xls,.csv"
                      className="w-full rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 px-4 py-4 text-sm font-medium text-slate-700 outline-none file:mr-4 file:rounded-xl file:border-0 file:bg-blue-600 file:px-4 file:py-2 file:text-xs file:font-black file:text-white hover:border-emerald-300"
                      onChange={(event) => setBulkUploadFile(event.target.files?.[0] || null)}
                    />
                    {bulkUploadFile ? <p className="text-xs font-bold uppercase tracking-widest text-slate-500">Selected: {bulkUploadFile.name}</p> : <p className="text-xs font-bold uppercase tracking-widest text-slate-400">Choose the completed Excel workbook.</p>}
                  </div>
                </div>
                <div className="flex gap-4 border-t border-slate-100 px-6 py-6 lg:px-8">
                  <button type="button" onClick={() => setIsBulkUploadModalOpen(false)} className="flex-1 rounded-2xl bg-slate-100 py-4 font-black text-slate-700 transition-all hover:bg-slate-200">Cancel</button>
                  <button type="submit" disabled={isBulkUploading} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-blue-600 py-4 font-black text-white shadow-sm transition-all hover:bg-blue-700 disabled:opacity-60">
                    {isBulkUploading ? 'Importing...' : 'Import Workbook'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        ) : null}

        {/* -- Assign Task Modal -------------------------------------------- */}
        {assigningTask ? (
          <div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#0F172A]/40 p-4 backdrop-blur-sm">
            <div className="flex w-full max-w-md flex-col overflow-hidden rounded-[2.5rem] bg-white shadow-2xl border border-white/70">
              <div className="flex items-center justify-between gap-4 border-b border-slate-100 bg-red-50/70 px-6 py-5">
                <div className="flex items-center gap-3">
                  <div className="rounded-xl bg-red-100 p-3 text-red-600"><User size={24} /></div>
                  <div>
                    <h2 className="text-xl font-black text-red-900">Assign Staff</h2>
                    <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-red-500">{assigningTask.roomName || assigningTask.taskName}</p>
                  </div>
                </div>
                <button onClick={() => { setAssigningTask(null); setTaskForm(taskFormState()); }} className="rounded-xl border border-slate-200 bg-white p-2 text-slate-500 transition-all hover:bg-slate-100"><X size={18} /></button>
              </div>
              <div className="p-6 space-y-4">
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-500">Select Housekeeping Staff</label>
                  <select className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-900 outline-none" value={taskForm.assigneeEmployeeProfileId} onChange={(event) => { const next = presentStaff.find((item) => item.id === event.target.value); setTaskForm({ ...taskForm, assigneeEmployeeProfileId: event.target.value, assignedTo: next?.label || '' }); }}>
                    <option value="">Select...</option>
                    {presentStaff.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}
                  </select>
                </div>
              </div>
              <div className="flex gap-4 border-t border-slate-100 bg-slate-50/30 px-6 py-5">
                <button onClick={() => { setAssigningTask(null); setTaskForm(taskFormState()); }} className="flex-1 rounded-2xl bg-white py-4 font-black text-slate-500 transition-all hover:text-slate-900">Cancel</button>
                <button disabled={!taskForm.assigneeEmployeeProfileId} onClick={assignTask} className="flex-1 rounded-2xl bg-red-600 py-4 font-black text-white shadow-sm transition-all hover:bg-red-700 disabled:bg-slate-300 disabled:shadow-none">Assign</button>
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </AppShell>
  );
}

// -- Sub-components ---------------------------------------------------------

function TasksTable({ tasks, onEdit, onCancel, emptyText }: TasksTableProps) {
  return (
    <div className="flex-1">
      <table className="w-full text-left table-auto">
        <thead className="bg-slate-50/50 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-slate-100/60">
          <tr>
            <th className="px-3 py-4 text-left whitespace-nowrap">Task Name & ID</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Area / Zone</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Floor / Wing</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Assigned To</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Start Time</th>
            <th className="px-3 py-4 text-center whitespace-nowrap">Status</th>
            <th className="px-3 py-4 text-center whitespace-nowrap w-28">Actions</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100/60">
          {tasks.map((task) => (
            <tr key={task.id} className="transition-colors hover:bg-blue-50/30">
              <td className="px-3 py-4 align-middle">
                <div className="text-xs font-black tracking-tight text-slate-900">{task.taskName}</div>
                <div className="mt-0.5 text-[9px] font-bold uppercase tracking-widest text-slate-400">{task.taskCode}</div>
              </td>
              <td className="px-3 py-4 align-middle text-xs font-bold text-slate-700">{task.area || 'General'}</td>
              <td className="px-3 py-4 align-middle text-xs font-bold text-slate-700">
                {task.floor || 'Any'}
                {task.wing ? ` / ${task.wing}` : ''}
              </td>
              <td className="px-3 py-4 align-middle">
                <span className="inline-flex items-center gap-1.5 text-xs font-black uppercase tracking-wider text-slate-600">
                  <User size={12} /> {task.assignedTo}
                </span>
              </td>
              <td className="px-3 py-4 align-middle">
                <span className="inline-flex items-center gap-1.5 text-xs font-black text-slate-600">
                  <Clock size={12} /> {task.startTaskTime ? formatTime12h(task.startTaskTime) : task.timeSlotLabel ? formatTime12h(task.timeSlotLabel) : 'Anytime'}
                </span>
              </td>
              <td className="px-3 py-4 align-middle text-center">
                <span className={`inline-flex rounded-full border px-2 py-0.5 text-[9px] font-black uppercase tracking-[0.22em] ${statusBadge(task.status)}`}>
                  {task.status}
                </span>
              </td>
              <td className="px-3 py-4 align-middle">
                <div className="flex items-center justify-center gap-1">
                  <button onClick={() => onEdit(task)} className="inline-flex items-center justify-center rounded-lg border border-gray-200 bg-white p-1.5 text-slate-500 shadow-sm transition hover:border-amber-200 hover:bg-amber-50 hover:text-amber-600" title="Edit Task">
                    <Edit size={13} />
                  </button>
                  <button onClick={() => onCancel(task)} className="inline-flex items-center justify-center rounded-lg border border-gray-200 bg-white p-1.5 text-slate-500 shadow-sm transition hover:border-red-200 hover:bg-red-50 hover:text-red-600" title="Cancel Task">
                    <Trash2 size={13} />
                  </button>
                </div>
              </td>
            </tr>
          ))}
          {tasks.length === 0 ? (
            <tr>
              <td colSpan={7} className="px-3 py-20 text-center">
                <ShieldAlert size={32} className="mx-auto text-slate-300 mb-3" />
                <p className="text-sm font-black uppercase tracking-widest text-slate-500">{emptyText}</p>
              </td>
            </tr>
          ) : null}
        </tbody>
      </table>
    </div>
  );
}

function AutoTasks({ tasks, onAssign, onDone }: AutoTasksProps) {
  return (
    <div className="flex-1 bg-slate-50/30">
      <div className="p-8">
        <div className="mx-auto mb-6 flex max-w-5xl items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4">
          <Zap className="mt-0.5 shrink-0 text-red-500" size={20} />
          <div className="text-xs font-medium leading-relaxed text-red-800">
            <strong>Automated System Trigger:</strong> Tasks below are generated from meeting room bookings and keep the room blocked until the clean-up is marked complete.
          </div>
        </div>
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-4">
          {tasks.map((task) => (
            <div key={task.id} className="flex flex-col gap-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-all hover:shadow-md md:flex-row md:items-center md:justify-between">
              <div className="flex flex-1 items-start gap-4">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-red-50 text-red-600">
                  <Sparkles size={24} />
                </div>
                <div>
                  <div className="flex flex-wrap items-center gap-3">
                    <h3 className="text-lg font-black text-slate-900">{task.roomName || task.taskName}</h3>
                    <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[9px] font-black uppercase text-amber-700">Requires Cleaning</span>
                  </div>
                  <p className="mt-1 text-xs font-bold text-slate-500">
                    Floor / Wing: <span className="text-slate-700">{task.floor || 'Any'}{task.wing ? ` / ${task.wing}` : ''}</span>
                  </p>
                  <p className="mt-1 text-xs font-bold text-slate-500">Booking Ended At: <span className="text-red-500">{task.bookingEndTimeLabel || 'Pending'}</span></p>
                  <p className="mt-2 flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-slate-400">Source: {task.sourceBookingCode || task.taskCode}</p>
                </div>
              </div>
              <div className="flex w-full items-center gap-4 md:w-auto">
                <div className="flex flex-col items-end">
                  <p className="mb-1 text-[10px] font-black uppercase tracking-widest text-slate-400">Assigned To</p>
                  {task.assignedTo === 'Unassigned' ? (
                    <span className="rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-500">Needs Assignment</span>
                  ) : (
                    <span className="flex items-center gap-1 text-xs font-bold text-slate-900"><User size={12} /> {task.assignedTo}</span>
                  )}
                </div>
                <div className="mx-2 hidden h-10 w-px bg-slate-200 md:block" />
                <button onClick={() => onAssign(task)} className="rounded-xl bg-slate-100 p-3 text-slate-600 transition-all hover:bg-blue-100 hover:text-blue-700" title="Assign Staff">
                  <User size={18} />
                </button>
                <button onClick={() => onDone(task)} className="flex items-center gap-2 rounded-xl bg-green-600 px-5 py-3 text-xs font-black text-white shadow-md shadow-green-200 transition-all hover:bg-green-700">
                  <CheckCircle2 size={16} /> Mark Done
                </button>
              </div>
            </div>
          ))}
          {tasks.length === 0 ? (
            <div className="py-20 text-center text-sm font-bold text-slate-400">No booking-based tasks pending.</div>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function HistoryTable({ tasks, month, year }: HistoryTableProps) {
  return (
    <div className="flex-1">
      <table className="w-full text-left table-auto">
        <thead className="bg-slate-50/50 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-slate-100/60">
          <tr>
            <th className="px-3 py-4 text-left whitespace-nowrap">Date</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Task Name & Details</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Area / Location</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Completed By</th>
            <th className="px-3 py-4 text-left whitespace-nowrap">Completion Time</th>
            <th className="px-3 py-4 text-center whitespace-nowrap">Status</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100/60">
          {tasks.map((task) => (
            <tr key={task.id} className="transition-colors hover:bg-blue-50/30">
              <td className="px-3 py-4 align-middle">
                <div className="flex items-center gap-1.5 text-xs font-bold text-slate-900">
                  <CalendarDays size={14} className="text-slate-400 shrink-0" />
                  {task.completedAtLabel || task.dueAtLabel || task.bookingDateLabel || 'Today'}
                </div>
                <div className="ml-5 mt-0.5 text-[9px] font-bold uppercase tracking-widest text-slate-400">{task.taskCode}</div>
              </td>
              <td className="px-3 py-4 align-middle text-xs font-bold text-slate-800">{task.taskName}</td>
              <td className="px-3 py-4 align-middle text-xs font-medium text-slate-600">{task.area || task.roomName || 'General'}</td>
              <td className="px-3 py-4 align-middle">
                <span className="flex items-center gap-1.5 text-xs font-bold text-slate-900">
                  <User size={14} className="text-slate-400 shrink-0" /> {task.completedBy || task.assignedTo || 'Admin'}
                </span>
              </td>
              <td className="px-3 py-4 align-middle text-xs font-black text-blue-600">{task.completedAt ? formatTime12h(task.completedAt) : 'Verbal'}</td>
              <td className="px-3 py-4 align-middle text-center">
                <span className="inline-flex items-center gap-1 rounded-full border border-green-200 bg-green-50 px-2 py-0.5 text-[9px] font-black uppercase tracking-[0.22em] text-green-600 whitespace-nowrap">
                  <Check size={12} /> Done
                </span>
              </td>
            </tr>
          ))}
          {tasks.length === 0 ? (
            <tr>
              <td colSpan={6} className="px-3 py-20 text-center">
                <p className="text-sm font-black uppercase tracking-widest text-slate-500">No historical data found for {month} {year}.</p>
              </td>
            </tr>
          ) : null}
        </tbody>
      </table>
    </div>
  );
}

// -- Exported Page Component ------------------------------------------------

export default function HousekeepingPage() {
  return (
    <HousekeepingErrorBoundary>
      <HousekeepingPageInner />
    </HousekeepingErrorBoundary>
  );
}
