import mongoose, { Document, Schema } from "mongoose";

export interface IHousekeepingTask extends Document {
    workspaceId: mongoose.Types.ObjectId;
    ownerId: mongoose.Types.ObjectId;
    taskNumber: number;
    taskCode: string;
    taskName: string;
    taskType: string;
    area?: string;
    floor?: string;
    wing?: string;
    assignedTo?: string;
    assigneeEmployeeProfileId?: mongoose.Types.ObjectId | null;
    sourceType: "manual" | "booking";
    sourceBookingId?: mongoose.Types.ObjectId;
    sourceBookingCode?: string;
    roomName?: string;
    roomType?: string;
    bookingDate?: Date | null;
    bookingStartTime?: string;
    bookingEndTime?: string;
    startTaskTime?: string;
    timeSlotLabel?: string;
    dueAt?: Date | null;
    notes?: string;
    status: "Pending" | "Assigned" | "In Progress" | "Completed" | "Cancelled";
    completionNote?: string;
    completedBy?: string;
    completedByUserId?: mongoose.Types.ObjectId | null;
    completedVia: "verbal" | "software";
    completedAt?: Date | null;
    isAutoGenerated: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

const housekeepingTaskSchema = new Schema<IHousekeepingTask>(
    {
        workspaceId: {
            type: Schema.Types.ObjectId,
            ref: "Workspace",
            required: true,
            index: true,
        },
        ownerId: {
            type: Schema.Types.ObjectId,
            ref: "HostUser",
            required: true,
            index: true,
        },
        taskNumber: {
            type: Number,
            required: true,
        },
        taskCode: {
            type: String,
            required: true,
            trim: true,
            index: true,
        },
        taskName: {
            type: String,
            required: true,
            trim: true,
            maxlength: 180,
        },
        taskType: {
            type: String,
            default: "Routine Cleaning",
            trim: true,
            maxlength: 80,
            index: true,
        },
        area: {
            type: String,
            default: "",
            trim: true,
            maxlength: 180,
        },
        floor: {
            type: String,
            default: "",
            trim: true,
            maxlength: 20,
        },
        wing: {
            type: String,
            default: "",
            trim: true,
            maxlength: 20,
        },
        assignedTo: {
            type: String,
            default: "Unassigned",
            trim: true,
            maxlength: 120,
        },
        assigneeEmployeeProfileId: {
            type: Schema.Types.ObjectId,
            ref: "EmployeeProfile",
            default: null,
            index: true,
        },
        sourceType: {
            type: String,
            enum: ["manual", "booking"],
            default: "manual",
            index: true,
        },
        sourceBookingId: {
            type: Schema.Types.ObjectId,
            ref: "MeetingRoomBooking",
            default: undefined,
            index: true,
        },
        sourceBookingCode: {
            type: String,
            default: "",
            trim: true,
            maxlength: 40,
        },
        roomName: {
            type: String,
            default: "",
            trim: true,
            maxlength: 120,
        },
        roomType: {
            type: String,
            default: "",
            trim: true,
            maxlength: 60,
        },
        bookingDate: {
            type: Date,
            default: null,
            index: true,
        },
        bookingStartTime: {
            type: String,
            default: "",
            trim: true,
        },
        bookingEndTime: {
            type: String,
            default: "",
            trim: true,
        },
        startTaskTime: {
            type: String,
            default: "",
            trim: true,
        },
        timeSlotLabel: {
            type: String,
            default: "",
            trim: true,
            maxlength: 120,
        },
        dueAt: {
            type: Date,
            default: null,
            index: true,
        },
        notes: {
            type: String,
            default: "",
            trim: true,
            maxlength: 2000,
        },
        status: {
            type: String,
            enum: ["Pending", "Assigned", "In Progress", "Completed", "Cancelled"],
            default: "Pending",
            required: true,
            index: true,
        },
        completionNote: {
            type: String,
            default: "",
            trim: true,
            maxlength: 2000,
        },
        completedBy: {
            type: String,
            default: "",
            trim: true,
            maxlength: 120,
        },
        completedByUserId: {
            type: Schema.Types.ObjectId,
            ref: "HostUser",
            default: null,
            index: true,
        },
        completedVia: {
            type: String,
            enum: ["verbal", "software"],
            default: "verbal",
            index: true,
        },
        completedAt: {
            type: Date,
            default: null,
            index: true,
        },
        isAutoGenerated: {
            type: Boolean,
            default: false,
            index: true,
        },
    },
    {
        timestamps: true,
    }
);

housekeepingTaskSchema.index({ ownerId: 1, taskNumber: 1 }, { unique: true });
housekeepingTaskSchema.index({ workspaceId: 1, taskNumber: 1 }, { unique: true, sparse: true });
housekeepingTaskSchema.index({ workspaceId: 1, createdAt: -1 });

export const HousekeepingTask = (mongoose.models.HousekeepingTask as mongoose.Model<IHousekeepingTask>) ||
    mongoose.model<IHousekeepingTask>("HousekeepingTask", housekeepingTaskSchema);
export default HousekeepingTask;
