// @ts-nocheck
import PDFDocument from "pdfkit";
import XLSX from "xlsx";

function escapeCsvValue(value = "") {
  return `"${String(value ?? "").replace(/"/g, '""')}"`;
}

function normalizeText(value = "") {
  return String(value ?? "").trim();
}

function normalizeMonthKey(value = "") {
  return normalizeText(value);
}

function formatReportDate(value) {
  if (!value) return "";
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
  });
}

export function buildReportCsv(report) {
  const reportRows = Array.isArray(report?.reportRows) ? report.reportRows : [];
  const monthlyData = Array.isArray(report?.monthlyData) ? report.monthlyData : [];

  const lines = [
    ["Field", "Value"],
    ["Report Code", report.reportCode],
    ["Title", report.title],
    ["Department", report.department || "General"],
    ["Category", report.category],
    ["Report Month", report.reportMonth || normalizeMonthKey(report.generatedAt)],
    ["Data Window", report.dataWindow || "Monthly"],
    ["Generated By", report.generatedBy],
    ["Generated Date", formatReportDate(report.generatedAt)],
    ["Period", report.period],
    ["Status", report.status],
    ["Description", report.description || ""],
  ].map((row) => row.map(escapeCsvValue).join(","));

  if (reportRows.length > 0) {
    lines.push("");
    lines.push(["Detail Label", "Detail Value"].map(escapeCsvValue).join(","));
    reportRows.forEach((row) => {
      lines.push([row.label, row.value].map(escapeCsvValue).join(","));
    });
  }

  if (monthlyData.length > 0) {
    lines.push("");
    lines.push(["Month", "Metric", "Value"].map(escapeCsvValue).join(","));
    monthlyData.forEach((row) => {
      lines.push([row.month, row.metric, row.value].map(escapeCsvValue).join(","));
    });
  }

  return lines.join("\n");
}

export function buildReportPdfBuffer(report) {
  const reportRows = Array.isArray(report?.reportRows) ? report.reportRows : [];
  const monthlyData = Array.isArray(report?.monthlyData) ? report.monthlyData : [];

  const doc = new PDFDocument({
    margin: 44,
    size: "A4",
    bufferPages: true,
  });

  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#0f172a").text(report?.title || "Department Report");
    doc.moveDown(0.25);

    doc.fontSize(10).fillColor("#475569");
    doc.text(`Report Code: ${report?.reportCode || ""}`);
    doc.text(`Department: ${report?.department || "General"}`);
    doc.text(`Category: ${report?.category || ""}`);
    doc.text(`Data Window: ${report?.dataWindow || "Monthly"}`);
    doc.text(`Report Month: ${report?.reportMonth || normalizeMonthKey(report?.generatedAt) || "N/A"}`);
    doc.text(`Generated By: ${report?.generatedBy || ""}`);
    doc.text(`Generated Date: ${formatReportDate(report?.generatedAt)}`);
    doc.text(`Period: ${report?.period || ""}`);

    doc.moveDown(0.75);

    if (report?.description) {
      doc.fontSize(11).fillColor("#111827").text(report.description, { width: 500 });
      doc.moveDown(0.7);
    }

    if (reportRows.length > 0) {
      doc.fontSize(13).fillColor("#0f172a").text("Report Summary");
      doc.moveDown(0.3);
      reportRows.forEach((row) => {
        doc.fontSize(10.5).fillColor("#111827").text(`${row.label}: ${row.value}`, { width: 500 });
      });
      doc.moveDown(0.6);
    }

    if (monthlyData.length > 0) {
      doc.fontSize(13).fillColor("#0f172a").text("Monthly Data");
      doc.moveDown(0.3);
      monthlyData.forEach((row) => {
        doc
          .fontSize(10.5)
          .fillColor("#111827")
          .text(`${row.month} | ${row.metric}: ${row.value}`, { width: 500 });
      });
      doc.moveDown(0.6);
    }

    doc.fontSize(9).fillColor("#64748b").text(
      `Downloaded from ${report?.reportCode || "report"} on ${new Date().toLocaleString("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
      })}`
    );

    doc.end();
  });
}

function buildReportWorkbook(report) {
  const reportRows = Array.isArray(report?.reportRows) ? report.reportRows : [];
  const monthlyData = Array.isArray(report?.monthlyData) ? report.monthlyData : [];

  const summaryRows = [
    ["Field", "Value"],
    ["Report Code", report?.reportCode],
    ["Title", report?.title],
    ["Department", report?.department || "General"],
    ["Category", report?.category],
    ["Report Month", report?.reportMonth || normalizeMonthKey(report?.generatedAt)],
    ["Data Window", report?.dataWindow || "Monthly"],
    ["Generated By", report?.generatedBy],
    ["Generated Date", formatReportDate(report?.generatedAt)],
    ["Period", report?.period],
    ["Status", report?.status],
    ["Description", report?.description || ""],
  ];

  const detailRows =
    reportRows.length > 0
      ? [["Label", "Value"], ...reportRows.map((r) => [r.label, r.value])]
      : [["Label", "Value"], ["No detail rows", ""]];

  const monthlyRows =
    monthlyData.length > 0
      ? [["Month", "Metric", "Value"], ...monthlyData.map((r) => [r.month, r.metric, r.value])]
      : [["Month", "Metric", "Value"], ["No monthly data", "", ""]];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet(summaryRows.map((r) => r.map((v) => v ?? ""))),
    "Summary"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet(detailRows.map((r) => r.map((v) => v ?? ""))),
    "Report Details"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet(monthlyRows.map((r) => r.map((v) => v ?? ""))),
    "Monthly Breakdown"
  );

  return workbook;
}

export function buildReportExcelBuffer(report) {
  const workbook = buildReportWorkbook(report);

  return XLSX.write(workbook, {
    type: "buffer",
    bookType: "xlsx",
    compression: true,
  });
}

export function safeMakeReportBaseName(value = "report") {
  const base = normalizeText(value)
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-zA-Z0-9-_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 120);

  return base || "report";
}

export async function buildReportFileBuffer(report, requestedFormat) {
  const fmt = normalizeText(requestedFormat || report?.format || "PDF").toUpperCase();
  const baseName = safeMakeReportBaseName(report?.title || report?.reportCode || "report");

  if (fmt === "EXCEL" || fmt === "XLSX" || fmt === "CSV") {
    const buffer = buildReportExcelBuffer(report);
    return {
      buffer,
      fileName: `${baseName}.xlsx`,
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      format: "Excel",
    };
  }

  const buffer = await buildReportPdfBuffer(report);
  return {
    buffer,
    fileName: `${baseName}.pdf`,
    mimeType: "application/pdf",
    format: "PDF",
  };
}

